name: CI
on: push
jobs:
  solve-puzzles:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        puzzle: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17.0.15
          cache: gradle
      - name: Compile
        run: ./gradlew compileKotlin
      - name: Solve
        run: ./gradlew solve -Puzzle=${{ matrix.puzzle }}